-- =============================================================================
--  Wi Padel Sherwood Pairs League - seed data
--  Generated by supabase/generate-seed.mjs - edit that script, not this file.
--
--  Run AFTER 01_schema.sql. Safe to re-run: it is idempotent and never
--  touches a result that has already been submitted.
-- =============================================================================

begin;

-- ------------------------------------------------------------------ divisions
insert into public.divisions (id, name, rating_label, sort_order) values
  ('intermediate', 'Intermediate', '1.5 - 3.0', 1),
  ('beginner',     'Beginner',     '0 - 1.5',   2)
on conflict (id) do update set
  name = excluded.name,
  rating_label = excluded.rating_label,
  sort_order = excluded.sort_order;

-- ------------------------------------------------------------------- settings
insert into public.league_settings (id) values (1) on conflict (id) do nothing;

-- Organiser PIN. CHANGE THIS before you share the site.
--   Default below is 'padel2026'.
insert into public.admin_credential (id, pin_hash)
values (1, extensions.crypt('padel2026', extensions.gen_salt('bf', 10)))
on conflict (id) do nothing;

-- --------------------------------------------------- Intermediate division
-- The 10 pairs from the league sheet. Phone numbers are left blank: add them
-- in the admin screen (or here) so players can contact each other directly.
insert into public.teams (id, division_id, seed, name, player1, player2, rating) values
  ('a1b2c3d4-0000-4000-8000-000000000001', 'intermediate', 1, 'Aktar / Ozayr', 'Aktar', 'Ozayr', 2.67),
  ('a1b2c3d4-0000-4000-8000-000000000002', 'intermediate', 2, 'ILY.R / Muzakkir', 'ILY.R', 'Muzakkir', 2.65),
  ('a1b2c3d4-0000-4000-8000-000000000003', 'intermediate', 3, 'Iqsaan / Ikram K.', 'Iqsaan', 'Ikram K.', 2.63),
  ('a1b2c3d4-0000-4000-8000-000000000004', 'intermediate', 4, 'Kyle / Wesley', 'Kyle', 'Wesley', 2.55),
  ('a1b2c3d4-0000-4000-8000-000000000005', 'intermediate', 5, 'Ryan / Nikhil', 'Ryan', 'Nikhil', 2.46),
  ('a1b2c3d4-0000-4000-8000-000000000006', 'intermediate', 6, 'Ismail / Muhammad', 'Ismail', 'Muhammad', 2.39),
  ('a1b2c3d4-0000-4000-8000-000000000007', 'intermediate', 7, 'JT / Rajiv', 'JT', 'Rajiv', 2.18),
  ('a1b2c3d4-0000-4000-8000-000000000008', 'intermediate', 8, 'Mohamed / Tash', 'Mohamed', 'Tash', 2.01),
  ('a1b2c3d4-0000-4000-8000-000000000009', 'intermediate', 9, 'Mohamed / Mohamed', 'Mohamed', 'Mohamed', 1.95),
  ('a1b2c3d4-0000-4000-8000-000000000010', 'intermediate', 10, 'Hamza / Yahya', 'Hamza', 'Yahya', 1.8)
on conflict (id) do update set
  name = excluded.name,
  player1 = excluded.player1,
  player2 = excluded.player2,
  rating = excluded.rating,
  seed = excluded.seed;

-- ------------------------------------------------------------------ fixtures
-- Full round robin: 10 teams, 9 rounds, 45 matches,
-- every pair once, hosting duty shared evenly. The host is simply the pair
-- asked to message first - matches can be played in any order.
insert into public.matches (division_id, round, match_no, home_team, away_team, status) values
  ('intermediate', 1,  1, 'a1b2c3d4-0000-4000-8000-000000000010', 'a1b2c3d4-0000-4000-8000-000000000001', 'pending'),
  ('intermediate', 1,  2, 'a1b2c3d4-0000-4000-8000-000000000009', 'a1b2c3d4-0000-4000-8000-000000000002', 'pending'),
  ('intermediate', 1,  3, 'a1b2c3d4-0000-4000-8000-000000000003', 'a1b2c3d4-0000-4000-8000-000000000008', 'pending'),
  ('intermediate', 1,  4, 'a1b2c3d4-0000-4000-8000-000000000004', 'a1b2c3d4-0000-4000-8000-000000000007', 'pending'),
  ('intermediate', 1,  5, 'a1b2c3d4-0000-4000-8000-000000000005', 'a1b2c3d4-0000-4000-8000-000000000006', 'pending'),
  ('intermediate', 2,  6, 'a1b2c3d4-0000-4000-8000-000000000009', 'a1b2c3d4-0000-4000-8000-000000000001', 'pending'),
  ('intermediate', 2,  7, 'a1b2c3d4-0000-4000-8000-000000000008', 'a1b2c3d4-0000-4000-8000-000000000010', 'pending'),
  ('intermediate', 2,  8, 'a1b2c3d4-0000-4000-8000-000000000002', 'a1b2c3d4-0000-4000-8000-000000000007', 'pending'),
  ('intermediate', 2,  9, 'a1b2c3d4-0000-4000-8000-000000000003', 'a1b2c3d4-0000-4000-8000-000000000006', 'pending'),
  ('intermediate', 2, 10, 'a1b2c3d4-0000-4000-8000-000000000004', 'a1b2c3d4-0000-4000-8000-000000000005', 'pending'),
  ('intermediate', 3, 11, 'a1b2c3d4-0000-4000-8000-000000000008', 'a1b2c3d4-0000-4000-8000-000000000001', 'pending'),
  ('intermediate', 3, 12, 'a1b2c3d4-0000-4000-8000-000000000007', 'a1b2c3d4-0000-4000-8000-000000000009', 'pending'),
  ('intermediate', 3, 13, 'a1b2c3d4-0000-4000-8000-000000000006', 'a1b2c3d4-0000-4000-8000-000000000010', 'pending'),
  ('intermediate', 3, 14, 'a1b2c3d4-0000-4000-8000-000000000002', 'a1b2c3d4-0000-4000-8000-000000000005', 'pending'),
  ('intermediate', 3, 15, 'a1b2c3d4-0000-4000-8000-000000000003', 'a1b2c3d4-0000-4000-8000-000000000004', 'pending'),
  ('intermediate', 4, 16, 'a1b2c3d4-0000-4000-8000-000000000007', 'a1b2c3d4-0000-4000-8000-000000000001', 'pending'),
  ('intermediate', 4, 17, 'a1b2c3d4-0000-4000-8000-000000000006', 'a1b2c3d4-0000-4000-8000-000000000008', 'pending'),
  ('intermediate', 4, 18, 'a1b2c3d4-0000-4000-8000-000000000005', 'a1b2c3d4-0000-4000-8000-000000000009', 'pending'),
  ('intermediate', 4, 19, 'a1b2c3d4-0000-4000-8000-000000000010', 'a1b2c3d4-0000-4000-8000-000000000004', 'pending'),
  ('intermediate', 4, 20, 'a1b2c3d4-0000-4000-8000-000000000002', 'a1b2c3d4-0000-4000-8000-000000000003', 'pending'),
  ('intermediate', 5, 21, 'a1b2c3d4-0000-4000-8000-000000000001', 'a1b2c3d4-0000-4000-8000-000000000006', 'pending'),
  ('intermediate', 5, 22, 'a1b2c3d4-0000-4000-8000-000000000005', 'a1b2c3d4-0000-4000-8000-000000000007', 'pending'),
  ('intermediate', 5, 23, 'a1b2c3d4-0000-4000-8000-000000000004', 'a1b2c3d4-0000-4000-8000-000000000008', 'pending'),
  ('intermediate', 5, 24, 'a1b2c3d4-0000-4000-8000-000000000009', 'a1b2c3d4-0000-4000-8000-000000000003', 'pending'),
  ('intermediate', 5, 25, 'a1b2c3d4-0000-4000-8000-000000000010', 'a1b2c3d4-0000-4000-8000-000000000002', 'pending'),
  ('intermediate', 6, 26, 'a1b2c3d4-0000-4000-8000-000000000001', 'a1b2c3d4-0000-4000-8000-000000000005', 'pending'),
  ('intermediate', 6, 27, 'a1b2c3d4-0000-4000-8000-000000000004', 'a1b2c3d4-0000-4000-8000-000000000006', 'pending'),
  ('intermediate', 6, 28, 'a1b2c3d4-0000-4000-8000-000000000003', 'a1b2c3d4-0000-4000-8000-000000000007', 'pending'),
  ('intermediate', 6, 29, 'a1b2c3d4-0000-4000-8000-000000000008', 'a1b2c3d4-0000-4000-8000-000000000002', 'pending'),
  ('intermediate', 6, 30, 'a1b2c3d4-0000-4000-8000-000000000009', 'a1b2c3d4-0000-4000-8000-000000000010', 'pending'),
  ('intermediate', 7, 31, 'a1b2c3d4-0000-4000-8000-000000000001', 'a1b2c3d4-0000-4000-8000-000000000004', 'pending'),
  ('intermediate', 7, 32, 'a1b2c3d4-0000-4000-8000-000000000003', 'a1b2c3d4-0000-4000-8000-000000000005', 'pending'),
  ('intermediate', 7, 33, 'a1b2c3d4-0000-4000-8000-000000000002', 'a1b2c3d4-0000-4000-8000-000000000006', 'pending'),
  ('intermediate', 7, 34, 'a1b2c3d4-0000-4000-8000-000000000007', 'a1b2c3d4-0000-4000-8000-000000000010', 'pending'),
  ('intermediate', 7, 35, 'a1b2c3d4-0000-4000-8000-000000000008', 'a1b2c3d4-0000-4000-8000-000000000009', 'pending'),
  ('intermediate', 8, 36, 'a1b2c3d4-0000-4000-8000-000000000001', 'a1b2c3d4-0000-4000-8000-000000000003', 'pending'),
  ('intermediate', 8, 37, 'a1b2c3d4-0000-4000-8000-000000000002', 'a1b2c3d4-0000-4000-8000-000000000004', 'pending'),
  ('intermediate', 8, 38, 'a1b2c3d4-0000-4000-8000-000000000005', 'a1b2c3d4-0000-4000-8000-000000000010', 'pending'),
  ('intermediate', 8, 39, 'a1b2c3d4-0000-4000-8000-000000000006', 'a1b2c3d4-0000-4000-8000-000000000009', 'pending'),
  ('intermediate', 8, 40, 'a1b2c3d4-0000-4000-8000-000000000007', 'a1b2c3d4-0000-4000-8000-000000000008', 'pending'),
  ('intermediate', 9, 41, 'a1b2c3d4-0000-4000-8000-000000000001', 'a1b2c3d4-0000-4000-8000-000000000002', 'pending'),
  ('intermediate', 9, 42, 'a1b2c3d4-0000-4000-8000-000000000010', 'a1b2c3d4-0000-4000-8000-000000000003', 'pending'),
  ('intermediate', 9, 43, 'a1b2c3d4-0000-4000-8000-000000000004', 'a1b2c3d4-0000-4000-8000-000000000009', 'pending'),
  ('intermediate', 9, 44, 'a1b2c3d4-0000-4000-8000-000000000005', 'a1b2c3d4-0000-4000-8000-000000000008', 'pending'),
  ('intermediate', 9, 45, 'a1b2c3d4-0000-4000-8000-000000000006', 'a1b2c3d4-0000-4000-8000-000000000007', 'pending')
on conflict (division_id, match_no) do nothing;

-- Beginner division starts empty on purpose - add its pairs in the admin
-- screen, then press "Generate fixtures" to build its 45 matches.

commit;
