/**
 * Regenerates 02_seed.sql.
 *
 * The fixture list is produced by the same `buildFixtures` used by the website
 * and covered by tests/core.test.mjs, so the seeded schedule and anything the
 * admin screen generates later come from one implementation.
 *
 *   node supabase/generate-seed.mjs
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { buildFixtures } from '../assets/js/core.js';

const here = dirname(fileURLToPath(import.meta.url));

/** Intermediate pairs, exactly as listed in the league sheet (ratings are the pair average). */
const INTERMEDIATE = [
  { name: 'Aktar / Ozayr',      p1: 'Aktar',   p2: 'Ozayr',    rating: 2.67 },
  { name: 'ILY.R / Muzakkir',   p1: 'ILY.R',   p2: 'Muzakkir', rating: 2.65 },
  { name: 'Iqsaan / Ikram K.',  p1: 'Iqsaan',  p2: 'Ikram K.', rating: 2.63 },
  { name: 'Kyle / Wesley',      p1: 'Kyle',    p2: 'Wesley',   rating: 2.55 },
  { name: 'Ryan / Nikhil',      p1: 'Ryan',    p2: 'Nikhil',   rating: 2.46 },
  { name: 'Ismail / Muhammad',  p1: 'Ismail',  p2: 'Muhammad', rating: 2.39 },
  { name: 'JT / Rajiv',         p1: 'JT',      p2: 'Rajiv',    rating: 2.18 },
  { name: 'Mohamed / Tash',     p1: 'Mohamed', p2: 'Tash',     rating: 2.01 },
  { name: 'Mohamed / Mohamed',  p1: 'Mohamed', p2: 'Mohamed',  rating: 1.95 },
  { name: 'Hamza / Yahya',      p1: 'Hamza',   p2: 'Yahya',    rating: 1.80 },
];

// Fixed UUIDs keep the seed file reproducible: re-running it produces an
// identical script, and fixtures keep pointing at the same teams.
const uuid = (n) => `a1b2c3d4-0000-4000-8000-${String(n).padStart(12, '0')}`;
const teamIds = INTERMEDIATE.map((_, i) => uuid(i + 1));

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);

const fixtures = buildFixtures('intermediate', teamIds);

const lines = [];
const out = (s = '') => lines.push(s);

out('-- =============================================================================');
out('--  Wi Padel Sherwood Pairs League - seed data');
out('--  Generated by supabase/generate-seed.mjs - edit that script, not this file.');
out('--');
out('--  Run AFTER 01_schema.sql. Safe to re-run: it is idempotent and never');
out('--  touches a result that has already been submitted.');
out('-- =============================================================================');
out('');
out('begin;');
out('');
out('-- ------------------------------------------------------------------ divisions');
out('insert into public.divisions (id, name, rating_label, sort_order) values');
out("  ('intermediate', 'Intermediate', '1.5 - 3.0', 1),");
out("  ('beginner',     'Beginner',     '0 - 1.5',   2)");
out('on conflict (id) do update set');
out('  name = excluded.name,');
out('  rating_label = excluded.rating_label,');
out('  sort_order = excluded.sort_order;');
out('');
out('-- ------------------------------------------------------------------- settings');
out('insert into public.league_settings (id) values (1) on conflict (id) do nothing;');
out('');
out('-- Organiser PIN. CHANGE THIS before you share the site.');
out("--   Default below is 'padel2026'.");
out('insert into public.admin_credential (id, pin_hash)');
out("values (1, extensions.crypt('padel2026', extensions.gen_salt('bf', 10)))");
out('on conflict (id) do nothing;');
out('');
out('-- --------------------------------------------------- Intermediate division');
out('-- The 10 pairs from the league sheet. Phone numbers are left blank: add them');
out('-- in the admin screen (or here) so players can contact each other directly.');
out('insert into public.teams (id, division_id, seed, name, player1, player2, rating) values');
const teamRows = INTERMEDIATE.map((t, i) =>
  `  (${q(teamIds[i])}, 'intermediate', ${i + 1}, ${q(t.name)}, ${q(t.p1)}, ${q(t.p2)}, ${t.rating})`);
out(teamRows.join(',\n'));
out('on conflict (id) do update set');
out('  name = excluded.name,');
out('  player1 = excluded.player1,');
out('  player2 = excluded.player2,');
out('  rating = excluded.rating,');
out('  seed = excluded.seed;');
out('');
out('-- ------------------------------------------------------------------ fixtures');
out(`-- Full round robin: ${INTERMEDIATE.length} teams, 9 rounds, ${fixtures.length} matches,`);
out('-- every pair once, hosting duty shared evenly. The host is simply the pair');
out('-- asked to message first - matches can be played in any order.');
out('insert into public.matches (division_id, round, match_no, home_team, away_team, status) values');
const fixtureRows = fixtures.map((f) =>
  `  ('intermediate', ${f.round}, ${String(f.match_no).padStart(2, ' ')}, ${q(f.home_team)}, ${q(f.away_team)}, 'pending')`);
out(fixtureRows.join(',\n'));
out('on conflict (division_id, match_no) do nothing;');
out('');
out('-- Beginner division starts empty on purpose - add its pairs in the admin');
out('-- screen, then press "Generate fixtures" to build its 45 matches.');
out('');
out('commit;');
out('');

writeFileSync(join(here, '02_seed.sql'), lines.join('\n'), 'utf8');

// Quick sanity report so a bad regeneration is obvious.
const hosts = new Map(teamIds.map((id) => [id, 0]));
for (const f of fixtures) hosts.set(f.home_team, hosts.get(f.home_team) + 1);
console.log(`Wrote 02_seed.sql: ${INTERMEDIATE.length} teams, ${fixtures.length} fixtures.`);
console.log(`Hosting duty per team: ${[...hosts.values()].join(', ')}`);
